#!/bin/sh
enable=$(uci get nat6-helper.@nat6-helper[0].enabled)

[ $enable = "0" ] && exit 0

res=`ip -6 route | grep "default from 2"`
gateway=`echo $res | awk '{print $5}'`
interface=`echo $res | awk '{print $7}'`
last_gw=$(ip -6 route | grep "2000::/3" | awk '{print $3}') #之前的网关地址
#由于网络变动后，网关地址可能变更，所以需要先获取之前的网关凑成删除路由表命令

if [ "$ACTION" = ifup ]; then
    ip -6 r add "2000::/3" via $gateway dev $interface
    if !(ip6tables-save -t nat | grep -q "v6NAT"); then
        ip6tables -t nat -A POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    fi
elif [ "$ACTION" = ifupdate ]; then
    ip -6 r del "2000::/3" via $last_gw dev $interface
    ip -6 r add "2000::/3" via $gateway dev $interface
    if !(ip6tables-save -t nat | grep -q "v6NAT"); then
        ip6tables -t nat -A POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    fi
elif [ "$ACTION" = ifdown ]; then
    ip -6 r del "2000::/3" via $last_gw dev $interface
    ip6tables -t nat -D POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
else
    exit 0
fi

