#!/bin/sh /etc/rc.common

START=99
STOP=10

EXTRA_COMMANDS="setLan"
EXTRA_HELP="set ULA and DHCPv6"

enable=$(uci get nat6-helper.@nat6-helper[0].enabled)
interface_public=$(uci get nat6-helper.@nat6-helper[0].name)

interface=$(uci get "network.$interface_public.ifname")             #获取选中的ipv6出口网口
gateway=$(ip -6 route | grep "default from 2" | awk '{print $5}')   #获取当前网关
last_gw=$(ip -6 route | grep "2000::/3" | awk '{print $3}')         #之前的网关地址
#由于网络变动后，网关地址可能变更，所以需要先获取之前的网关凑成删除路由表命令
#原先的default via命令有可能会冲突，所以改用nat6脚本中的只路由到公网的ip，即2开头的ip

setLan() 
{
    uci set network.globals.ula_prefix='fd00::/64'
	uci set dhcp.lan.dhcpv6='server'
	uci set dhcp.lan.ra='server'
	uci set dhcp.lan.ra_default='1'
	uci set dhcp.lan.ra_management='1'
	uci commit network
    logger -t nat6-helper "ULA and DHCPv6 have been set"
}

start() {
	[ $enable = "0" ] && exit 0
    if (ip -6 route | grep -q "2000::/3"); then
        #删除之前在路由表给想访问公网ip的数据包设置的路由器上级网关
        ip -6 r del "2000::/3" v ia $last_gw dev $interface
    fi
    #由于网卡变动也许路由器上级网关也变了，所以需要先删除原先设置的网关，再设置最新网关
    ip -6 r add "2000::/3" via $gateway dev $interface > /dev/null 2>&1

    #设置nat6，与上面相同
    if !(ip6tables-save -t nat | grep -q "v6NAT"); then
        ip6tables -t nat -A POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    fi

    logger -t nat6-helper "Routing rule and firewall NAT6 rule have been set"
}

stop() {
    if (ip -6 route | grep -q "2000::/3"); then
        #删除之前在路由表给想访问公网ip的数据包设置的路由器上级网关
        ip -6 r del "2000::/3" via $last_gw dev $interface
    fi
    #删除nat6设置
    if (ip6tables-save -t nat | grep -q "v6NAT"); then
        ip6tables -t nat -D POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    fi

    logger -t nat6-helper "Routing rule and firewall NAT6 rule have been delete"
}